"""Node: GitAgent — применяет изменения и создаёт коммит/ветку/PR.

Выполняется только после Human Approval.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from gib.core.state import GibState
from gib.core.types import PatchFile
from gib.utils import get_logger

logger = get_logger("gib.nodes.git")


def _run_git(args: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=30,
        check=check,
    )


def _sanitize_branch_name(name: str) -> str:
    """Превращает задачу в валидное имя ветки."""
    import re
    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9\-_]", "-", name)
    name = re.sub(r"-+", "-", name)
    return f"gib/{name[:50]}"


def _write_patches(patch_files: list[PatchFile], root: Path) -> list[str]:
    """Записывает изменённые файлы на диск."""
    written: list[str] = []
    for pf in patch_files:
        abs_path = root / pf.path
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(pf.modified, encoding="utf-8")
        written.append(pf.path)
        logger.info("[git] Записан файл: %s", pf.path)
    return written


async def node_git(state: GibState) -> dict:
    """
    LangGraph Node: применяет патч и создаёт коммит.
    """
    root = Path(state.get("project_context", {}).get("root", str(Path.cwd())))
    patch_files: list[PatchFile] = state.get("patch_files", [])
    user_request = state.get("user_request", "")
    commit_msg = state.get("commit_message", "")
    workflow_type = state.get("workflow_type", "feature")

    if not patch_files:
        logger.warning("[git] Нет файлов для применения")
        return {
            "success": True,
            "final_output": state.get("code_result", ""),
            "current_step": "done",
            "logs": ["[Git] No patch files to apply, skipping git operations"],
        }

    logs: list[str] = []
    warnings: list[str] = []

    # Проверяем git
    git_info = state.get("repository_context", {})
    if not git_info.get("has_git"):
        logger.warning("[git] Git не инициализирован, пропускаю")
        written = _write_patches(patch_files, root)
        return {
            "success": True,
            "final_output": state.get("code_result", ""),
            "current_step": "done",
            "logs": [f"[Git] Applied {len(written)} files (no git repo)"],
            "warnings": ["No git repository found, files written without git commit"],
        }

    # Создаём ветку
    branch_name = _sanitize_branch_name(
        state.get("branch_name") or f"{workflow_type}-{user_request[:40]}"
    )

    try:
        _run_git(["checkout", "-b", branch_name], root)
        logs.append(f"[Git] Created branch: {branch_name}")
    except subprocess.CalledProcessError:
        try:
            _run_git(["checkout", branch_name], root)
            logs.append(f"[Git] Switched to branch: {branch_name}")
        except subprocess.CalledProcessError as e:
            warnings.append(f"Could not create/switch branch: {e.stderr}")
            branch_name = git_info.get("branch", "main")

    # Записываем файлы
    written = _write_patches(patch_files, root)
    logs.append(f"[Git] Written {len(written)} files")

    # git add
    try:
        for fp in written:
            _run_git(["add", fp], root)
        logs.append("[Git] Files staged")
    except subprocess.CalledProcessError as e:
        warnings.append(f"git add failed: {e.stderr}")

    # Генерируем commit message если нет
    if not commit_msg:
        prefix = {
            "feature": "feat",
            "bugfix": "fix",
            "refactor": "refactor",
            "review": "review",
            "explain": "docs",
            "doctor": "chore",
        }.get(workflow_type, "feat")
        commit_msg = f"{prefix}: {user_request[:72]}"

    # git commit
    try:
        result = _run_git(["commit", "-m", commit_msg], root)
        logs.append(f"[Git] Committed: {commit_msg}")
        logger.info("[git] Коммит создан: %s", commit_msg)
    except subprocess.CalledProcessError as e:
        warnings.append(f"git commit failed: {e.stderr}")
        logger.warning("[git] Commit failed: %s", e.stderr)

    # PR description
    pr_description = (
        f"## Changes\n{state.get('approval_summary', '')}\n\n"
        f"## Review\n{state.get('review_result', '')[:1000]}\n\n"
        f"---\n*Generated by GIB AI Pipeline*"
    )

    return {
        "success": True,
        "branch_name": branch_name,
        "commit_message": commit_msg,
        "pr_description": pr_description,
        "final_output": state.get("code_result", ""),
        "current_step": "done",
        "logs": logs,
        "warnings": warnings,
    }
